# Generated by Django 3.2.14 on 2022-08-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_data',
            new_name='posted_date',
        ),
    ]
